### PR TITLE
allow overwriting DB_FILTER when starting a container

### PR DESCRIPTION
**Pull request by ap-wtioit**
Our usecase: a website user should be able to connect to the odoo instance without selecting the database first.

The problem: the default `dbfilter = .*` in the /opt/odoo/auto/odoo.conf (Given by build `ENV DB_FILTER=.*`) cannot be overwritten when starting a container. We also do not want to add https://github.com/OCA/server-tools/tree/11.0/dbfilter_from_header yet.

this enables setting DB_FILTER in environment when starting a container
e.g. in devel.yaml

info @wt-io-it

### CODE REVIEW

**Comment by Yajo** [comment]
When the container boots for the first time, it checks if a `/opt/odoo/auto/odoo.conf` file exists. If it doesn't, it generates it by applying the templates and expanding env variables.

You can check the code here: https://github.com/Tecnativa/doodba/blob/5c74086081f202110a06c46de78e53dbabe13a51/entrypoint.d/50-config-generate#L3-L8

`/opt/odoo/auto/odoo.conf` is not present by default, and usually changing a variable will force a container reconstruction when you run `docker-compose up -d` again, all that process should be automatically triggered.

So, how would I reproduce that problem?

**Comment by ap-wtioit** [comment]
the environment part from my devel.yaml:
```
        environment:
            PIP_INSTALL_ODOO: "false"
            ADMIN_PASSWORD: admin
            PTVSD_ENABLE: "${DOODBA_PTVSD_ENABLE:-0}"
            PGDATABASE: "{PGDATABASE:-devel}"
            DB_FILTER: "${DB_FILTER:-^devel$}"
            PYTHONOPTIMIZE: ""
            SMTP_PORT: "1025"
            # You want demo data for development
            WITHOUT_DEMO: "false"
            ENABLE_PYDEVD: "${ENABLE_PYDEVD:-false}"
```

And i tried to run (to see if config is representing the values):
```
DB_FILTER=^devel$ PGDATABASE=devel docker-compose -f devel.yaml run --rm odoo cat /opt/odoo/auto/odoo.conf
DB_FILTER=^devel1$ PGDATABASE=devel1 docker-compose -f devel.yaml run --rm odoo cat /opt/odoo/auto/odoo.conf
DB_FILTER=^devel2$ PGDATABASE=devel2 docker-compose -f devel.yaml run --rm odoo cat /opt/odoo/auto/odoo.conf
```

**Comment by Yajo** [comment]
Could that be some problem with quoting? I'm doing the same and it works fine... :thinking: 

peek 01-03-2019 08-16

Please make sure you're using the latest scaffolding.

**Comment by pedrobaeza** [comment]
@Yajo have you tried with bash instead of fish?

**Comment by Yajo** [comment]
Same results.

<details>

```
yajo@yajolap:~/D/d/t/doodbadevel12|12.0⚡*?
➤ bash
[yajo@yajolap doodbadevel12]$ git diff devel.yaml
diff --git a/devel.yaml b/devel.yaml
index 9920fdd..4e15f71 100644
--- a/devel.yaml
+++ b/devel.yaml
@@ -29,6 +29,7 @@ services:
                 COMPILE: "false"
                 DEFAULT_REPO_PATTERN_ODOO: "https://github.com/odoo/odoo.git"
         environment:
+            DB_FILTER: $DB_FILTER
             ADMIN_PASSWORD: admin
             DOODBA_ENVIRONMENT: devel
             PTVSD_ENABLE: "${DOODBA_PTVSD_ENABLE:-0}"
@@ -41,6 +42,7 @@ services:
         volumes:

[yajo@yajolap doodbadevel12]$  DB_FILTER=HELLO docker-compose run --rm odoo cat auto/odoo.conf | grep dbfilter
Starting doodbadevel12_google_proxy_1_a5dd40a48449           ... done
Starting doodbadevel12_fonts_googleapis_proxy_1_92b3b85de921 ... done
Starting doodbadevel12_fonts_gstatic_proxy_1_886a7a0454e8    ... done
Starting doodbadevel12_wdb_1_cb45de0b4cb2                    ... done
Starting doodbadevel12_smtp_1_ed2f518add39                   ... done
Starting doodbadevel12_db_1_1190423d8688                     ... done
Starting doodbadevel12_gravatar_proxy_1_78d1160860e9         ... done
Starting doodbadevel12_cdnjs_cloudflare_proxy_1_36857d2efd45 ... done
dbfilter = HELLO
```

</details>

**Comment by ap-wtioit** [comment]
Tested with the official images and it seems to be a issue with our adaptations (works with https://github.com/Tecnativa/doodba-scaffolding on my system as well without the patch), sorry for bothering you.

**Comment by Yajo** [comment]
No problem :wink:

**Pull request closed without merging**
