### PR TITLE
[ADD] New geoip configuration file to provide odoo_version>=17.0 compatibility

### PR DESCRIPTION
**Pull request by josep-tecnativa**
CC @Tecnativa TT48174
In order to fix this issue, https://github.com/Tecnativa/doodba/issues/600 

Not tested yet.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This only applies to v17. Why are you doing this in all versions?

**Comment by josep-tecnativa** [comment]
> This only applies to v17. Why are you doing this in all versions?
The changes I've made are to use the configuration file 60-geoip.conf for versions < 17.0, and for versions >= 17.0, to use 70-geoip.conf. To achieve this, for versions <17.0, I delete the file 70-geoip.conf:
`RUN rm common/conf.d/70-geoip.conf`
And for version 17.0, I delete 60-geoip.conf:
`RUN rm common/conf.d/60-geoip.conf`

**Comment by ap-wtioit** [comment]
This would probably also need to be reflected in the [test code](https://github.com/Tecnativa/doodba/blob/master/tests/__init__.py#L612):
```python
                    # verify that geoip database is configured
                    (
                        "grep",
                        "-R",
                        "geoip_database = /opt/odoo/auto/geoip/GeoLite2-City.mmdb",
                        "/opt/odoo/auto/odoo.conf",
                    ),
```

**Comment by pedrobaeza** [comment]
Superseded by #603

**Pull request closed without merging**
