### PR TITLE
[IMP] tests: add test for screencast

### PR DESCRIPTION
**Pull request by ap-wtioit**
and verify artifacts are stored

[as discussed](https://github.com/Tecnativa/doodba/pull/599#issuecomment-1970619224) with @chienandalu we should add a test to ensure chrome is working as expected in doodba for http test cases

This is failing for 17.0 (showing that the test is detecting missing artifacts) and should start getting passes once https://github.com/odoo/odoo/pull/156738 lands in 17.0.

Info @wt-io-it

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for improving this, Andreas. Waiting for the merge of the other PR to merge this one.

**Review by chienandalu — APPROVED** [review]
Great :-1:

**Comment by ap-wtioit** [comment]
Missing proper UID/permissions for artifacts directory on github CI:
```
2024-03-05 11:21:00,629 1 INFO prod odoo.addons.base.tests.test_http_case: Starting TestChromeBrowser.test_screencasts ... 
2024-03-05 11:21:00,632 1 INFO prod odoo.addons.base.tests.test_http_case: ====================================================================== 
2024-03-05 11:21:00,632 1 ERROR prod odoo.addons.base.tests.test_http_case: ERROR: TestChromeBrowser.test_screencasts
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/tests/test_http_case.py", line 52, in setUp
    self.browser = ChromeBrowser(logger, '1366x768', "TestChromeBrowser")
  File "/opt/odoo/custom/src/odoo/odoo/tests/common.py", line 933, in __init__
    os.makedirs(self.screenshots_dir, exist_ok=True)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/odoo/auto/test-artifacts/prod'
```

**Comment by pedrobaeza** [comment]
Something that I should fix? How?

**Comment by ap-wtioit** [comment]
no, i will handle it, i need to use the same docker-compose + sub_env file as in other tests that expose files / directories (but i copied from smallest and my local uid is 1000 so i didn't notice that when testing locally)

**Comment by ap-wtioit** [comment]
Notes for/from testing:
* .mp4 file is not compatible with Totem, but playing with VLC works

**Comment by chienandalu** [comment]
> This is failing for 17.0 (showing that the test is detecting missing artifacts) and should start getting passes once [odoo/odoo#156341](https://github.com/odoo/odoo/pull/156341) is merged.

Looks like it's already merged :)

**Comment by ap-wtioit** [comment]
Oh i got the wrong one, seems the forward porting of "add test for screencast" is stuck at [16.4](https://github.com/odoo/odoo/pull/155951) and no forward port PR is created for 17.0 yet.

**Comment by chienandalu** [comment]
Oh, I didn't double check either :sweat_smile:

**Comment by ap-wtioit** [comment]
now we have the test also in 17.0 https://github.com/odoo/odoo/blob/17.0/odoo/addons/base/tests/test_http_case.py, can anybody retry the test?

**Comment by chienandalu** [comment]
I just hit it :)

**Comment by ap-wtioit** [comment]
ok, doodba is using OCB as default, so the test did not work because [test_screencasts is still missing there](https://github.com/OCA/OCB/blob/17.0/odoo/addons/base/tests/test_http_case.py) but it will land there soon enough i guess.

**Review by chienandalu — APPROVED** [review]
Tests passed :slightly_smiling_face: :+1:

**Pull request merged**
